# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_html:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: ZacJW/markdown-html-action@1.1.0
        with:
          input_files: '[["SealDice*.md"]]'
          output_files: '["html/SealDice 指令手册.html"]'
          
  html_dir_to_gh-pages:
    runs-on: ubuntu-latest
    name: HTML dir to gh-pages
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Running the HTML dir to gh-pages Action
        uses: uibcdf/action-html-dir-to-gh-pages@v1.0.0
        with:
          branch: master
          html_dir: html
